    <ext_attributes>
      <req_serv_id>${PC_TRACODE}</req_serv_id>
      <iterate_no>${DATA.itemslist?size}</iterate_no>
      <requester_id>82</requester_id>
      <channel_id>82</channel_id>
      <ori_req_id>82</ori_req_id>
      <ori_cha_id>${channel_id}</ori_cha_id>
      <req_servcode>${cardid}</req_servcode>
      <channel_servcode>${cardid}</channel_servcode>
      <ori_req_servcode>${req_servcode}</ori_req_servcode>
      <ori_cha_servcode>${channel_servcode}</ori_cha_servcode>
      <terminal_id>${terminal_id}</terminal_id>
      <branch_id>${branch_id}</branch_id>
      <operator_id>${operator_id}</operator_id>
      <sub_auth_teller></sub_auth_teller>
      <auth_psw01></auth_psw01>
      <bran_auth_teller></bran_auth_teller>
      <auth_psw02></auth_psw02>
      <cen_auth_teller01></cen_auth_teller01>
      <auth_psw03></auth_psw03>
      <cen_auth_teller02></cen_auth_teller02>
      <ori_req_date>${ori_req_date}</ori_req_date>
      <ori_req_sn>${terminal_id}${ori_req_sn}</ori_req_sn>
      <ori_req_timestamp>${service_time}</ori_req_timestamp>
      <requester_date>${catrdt}</requester_date>
      <requester_sn>${cardsq}</requester_sn>
      <mac_value></mac_value>
    </ext_attributes>
    