<?xml version="1.0" encoding="UTF-8"?>
<Service>
  <Service_Header>
    <service_id>${s_service_id?html}</service_id>
    <requester_id>${s_requester_id?html}</requester_id>
    <channel_id>${s_channel_id?html}</channel_id>
    <service_time>${s_service_time?html}</service_time>
    <version_id>${s_version_id?html}</version_id>
    <route_flag>${s_route_flag?html}</route_flag>
    <common>${s_common?html}</common>
  </Service_Header>
  <Service_Body>
    <ext_attributes>
      <req_serv_id>${req_serv_id?html}</req_serv_id>
      <iterate_no>${iterate_no?html}</iterate_no>
      <requester_id>${requester_id?html}</requester_id>
      <channel_id>${channel_id?html}</channel_id>
      <ori_req_id>${ori_req_id?html}</ori_req_id>
      <ori_cha_id>${ori_cha_id?html}</ori_cha_id>
      <req_servcode>${req_servcode?html}</req_servcode>
      <channel_servcode>${channel_servcode?html}</channel_servcode>
      <ori_req_servcode>${ori_req_servcode?html}</ori_req_servcode>
      <ori_cha_servcode>${ori_cha_servcode?html}</ori_cha_servcode>
      <terminal_id>${terminal_id?html}</terminal_id>
      <branch_id>${branch_id?html}</branch_id>
      <operator_id>${operator_id?html}</operator_id>
      <sub_auth_teller>${sub_auth_teller?html}</sub_auth_teller>
      <auth_psw01>${auth_psw01?html}</auth_psw01>
      <bran_auth_teller>${bran_auth_teller?html}</bran_auth_teller>
      <auth_psw02>${auth_psw02?html}</auth_psw02>
      <cen_auth_teller01>${cen_auth_teller01?html}</cen_auth_teller01>
      <auth_psw03>${auth_psw03?html}</auth_psw03>
      <cen_auth_teller02>${cen_auth_teller02?html}</cen_auth_teller02>
      <ori_req_date>${ori_req_date?html}</ori_req_date>
      <ori_req_sn>${ori_req_sn?html}</ori_req_sn>
      <ori_req_timestamp>${ori_req_timestamp?html}</ori_req_timestamp>
      <requester_date>${requester_date?html}</requester_date>
      <requester_sn>${requester_sn?html}</requester_sn>
      <mac_value>${mac_value?html}</mac_value>
    </ext_attributes>
    <request>
    </request>
  </Service_Body>
</Service>